{% set version = "0.10.0" %}

package:
  name: nbgitpuller
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbgitpuller/nbgitpuller-{{ version }}.tar.gz
  sha256: 57c61d9a163b2dbcc59237e5ae9588586320493c8c968fde2b632afeae2afc71

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gitpuller = nbgitpuller.pull:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - notebook >=5.5.0
    - tornado

test:
  requires:
    - pip
  imports:
    - nbgitpuller
  commands:
    - pip check
    - gitpuller --help

about:
  home: https://github.com/data-8/nbgitpuller
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Notebook Extension to do one-way synchronization of git repositories

extra:
  recipe-maintainers:
    - ocefpaf
