{% set version = "1.2.2" %}

package:
  name: nbgitpuller
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nbgitpuller/nbgitpuller-{{ version }}.tar.gz
  sha256: 3a3dfe985642738ac01acba29e6703a2cd2468dd768b6f004eb74e836d22515d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - gitpuller = nbgitpuller.pull:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    # pyproject.toml doesn't seem to be respected, due to this, we need to
    # explicitly make our build dependency jupyter-packaging available. This
    # could be resolved also by wrapping the setup.py's use of jupyter-packaging
    # within a try/catch block.
    #
    # See https://github.com/conda/conda-build/issues/3507 and
    # https://github.com/jupyter/jupyter-packaging#as-a-build-requirement for
    # more relevant details.
    #
    - jupyter-packaging
  run:
    - python >={{ python_min }}
    - jupyter_server >=1.10.1
    - notebook >=5.5.0
    - tornado

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - nbgitpuller
  commands:
    - pip check
    - gitpuller --help

about:
  home: https://github.com/data-8/nbgitpuller
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Notebook Extension to do one-way synchronization of git repositories

extra:
  recipe-maintainers:
    - ocefpaf
    - consideratio
