{% set version = "1.1.0" %}

package:
  name: nbgitpuller
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbgitpuller/nbgitpuller-{{ version }}.tar.gz
  sha256: 81821eaaf130f7757bb59b162c1c4da1fcc84d1a1f27177a04c07bf55c30df05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gitpuller = nbgitpuller.pull:main

requirements:
  host:
    - python >=3
    - pip
    # pyproject.toml doesn't seem to be respected, due to this, we need to
    # explicitly make our build dependency jupyter-packaging available. This
    # could be resolved also by wrapping the setup.py's use of jupyter-packaging
    # within a try/catch block.
    #
    # See https://github.com/conda/conda-build/issues/3507 and
    # https://github.com/jupyter/jupyter-packaging#as-a-build-requirement for
    # more relevant details.
    #
    - jupyter-packaging
  run:
    - python >=3
    - jupyter_server >=1.10.1
    - notebook >=5.5.0
    - tornado

test:
  requires:
    - pip
  imports:
    - nbgitpuller
  commands:
    - pip check
    - gitpuller --help

about:
  home: https://github.com/data-8/nbgitpuller
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Notebook Extension to do one-way synchronization of git repositories

extra:
  recipe-maintainers:
    - ocefpaf
    - consideratio
