travis:
  secure:
    BINSTAR_TOKEN: W2Ie4p+JoaMAfJoZezdTl9H752s9KYiEyM9sw9DXX6N/GqasXhaR+Ap4MN25HAl0hwn9NrPsXhjWpTfZvTqU09iwGVi0jPpuDswbnLBf/eTSa73GCsNhFp1TnyivrGJlleaxq+0zqftFDMMdYqm/U1KXll41spfOxq5F8oavETAKn3RJAvZic9F31Fo3P4IEAes9Maw311d4r5/TvEFURtE4OGSV14UOzhdaPqa7tWcvYxb2JJ2kB+F0ljlQl0TJ7yf+RKm8bgcARSgE+eF9l6vB8TJ09vTVCdNc5UP7si6mklFr/zLDE/s2D7cpUDJPJ49XCF6DXey9bxurijS079boq34Pi519YNJRiDZXBlEmPa6pleYW1QABi+fCj82WaIq/FXU9CcPihyHs6O6CE2EoNV8xt9XHSDO0Q3Ll1MqEbImZ+eomZY7SX3rwwT5ZUcprWYrtHMvqw1oJq7qBfnPqQ/2o2be3OChVmrVNlPSzpgkNDSwGpRIi57khSYDm0YpU/SdR7y+v1MOv5aMIekWOYXPODkgKIv/K1F3mjF2Q9IsZHbEt8UoBxcGhIrHxtIpVQ0wHQzpBkYOaAHJpQnnCoEGjg7Qn5czPgHHpcyUwR6LipG4QXgrt+w4E02zWPybgJgfNxgDj4UO3gtNg56qJ+4OXev1OODeF6kKO2gk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
